In [2]:
import pandas as pd
from sklearn.datasets import fetch_california_housing

# Veri setini yükleme
housing = fetch_california_housing(as_frame=True)
df = housing.frame

In [3]:
df.head(1)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.02381,322.0,2.555556,37.88,-122.23,4.526

In [7]:
df.shape

(20640, 9)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   MedInc       20640 non-null  float64
 1   HouseAge     20640 non-null  float64
 2   AveRooms     20640 non-null  float64
 3   AveBedrms    20640 non-null  float64
 4   Population   20640 non-null  float64
 5   AveOccup     20640 non-null  float64
 6   Latitude     20640 non-null  float64
 7   Longitude    20640 non-null  float64
 8   MedHouseVal  20640 non-null  float64
dtypes: float64(9)
memory usage: 1.4 MB

In [4]:
df.isnull().sum()

MedInc         0
HouseAge       0
AveRooms       0
AveBedrms      0
Population     0
AveOccup       0
Latitude       0
Longitude      0
MedHouseVal    0
dtype: int64

In [5]:
# Eğitim öncesi herşey hazır

In [30]:
from sklearn.model_selection import train_test_split

x = df.drop(columns=["MedHouseVal"])
y =df['MedHouseVal']

In [31]:
# Eğitim ve Test verisini ayıralım
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [32]:
# Verileri Ölçeklendirme yapalım
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [33]:
# Lineer Regresyon modelini kuralım
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [34]:
tahmin = model.predict(x_test)

In [35]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
r2 = r2_score(y_test, tahmin)
mse = mean_squared_error(y_test, tahmin)
mae = mean_absolute_error(y_test, tahmin)

In [36]:
print(f"Model Test R² Skoru: {r2:.4f}")
print(f"Mean Squared Error (MSE): {mse:.4f}")
print(f"Mean Absolute Error (MAE): {mae:.4f}")

Model Test R² Skoru: 0.5758
Mean Squared Error (MSE): 0.5559
Mean Absolute Error (MAE): 0.5332

In [37]:
# Şimdi Algo Test ile yapalım
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
pd.set_option("display.max_columns",100)

from sklearn.linear_model import LinearRegression,SGDRegressor,Ridge,Lasso,ElasticNet
from sklearn.neighbors import KNeighborsRegressor, RadiusNeighborsRegressor
from sklearn.ensemble import GradientBoostingRegressor,AdaBoostRegressor
from sklearn.tree import DecisionTreeRegressor, plot_tree, ExtraTreeRegressor
#pip install xgboost
from xgboost import XGBRegressor
from sklearn.svm import SVR

from sklearn.neural_network import MLPRegressor

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

def algo_test(x,y):
        #Bütün modelleri tanımlıyorum
        L=LinearRegression()
        R=Ridge()
        Lass=Lasso()
        E=ElasticNet()
        sgd=SGDRegressor()
        ETR=ExtraTreeRegressor()
        GBR=GradientBoostingRegressor()
        kn=KNeighborsRegressor()
        rkn=RadiusNeighborsRegressor(radius=1.0)
        ada=AdaBoostRegressor()
        dt=DecisionTreeRegressor()
        xgb=XGBRegressor()
        svr=SVR()
        mlp_regressor = MLPRegressor()



        algos=[L,R,Lass,E,sgd,ETR,GBR,ada,kn,dt,xgb,svr,mlp_regressor]
        algo_names=['Linear','Ridge','Lasso','ElasticNet','SGD','Extra Tree','Gradient Boosting',
                    'KNeighborsRegressor','AdaBoost','Decision Tree','XGBRegressor','SVR','mlp_regressor']
        x=MinMaxScaler().fit_transform(x)
        x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=.20,random_state=42)

        r_squared= []
        rmse= []
        mae= []

        #Hata ve doğruluk oranlarını bir tablo haline getirmek için bir dataframe oluşturuyorum
        result=pd.DataFrame(columns=['R_Squared','RMSE','MAE'],index=algo_names)


        for algo in algos:
            p=algo.fit(x_train,y_train).predict(x_test)
            r_squared.append(r2_score(y_test,p))
            rmse.append(mean_squared_error(y_test,p)**.5)
            mae.append(mean_absolute_error(y_test,p))



        #result adlı tabloya doğruluk ve hata oranlarımı yerleştiriyorum
        result.R_Squared=r_squared
        result.RMSE=rmse
        result.MAE=mae

       #oluşturduğum result tablosunu doğruluk oranına (r2_score) göre sıralayıp dönüyor
        rtable=result.sort_values('R_Squared',ascending=False)
        return rtable

In [38]:
algo_test(x,y)

                     R_Squared      RMSE       MAE
XGBRegressor          0.836659  0.462648  0.310742
Gradient Boosting     0.775629  0.542234  0.371709
AdaBoost              0.689246  0.638134  0.426665
mlp_regressor         0.679025  0.648543  0.437706
SVR                   0.638268  0.688489  0.458360
Decision Tree         0.621767  0.704017  0.453958
Ridge                 0.584124  0.738220  0.539215
Linear                0.575788  0.745581  0.533200
SGD                   0.551130  0.766944  0.564221
Extra Tree            0.547856  0.769736  0.500813
KNeighborsRegressor   0.463353  0.838587  0.716621
ElasticNet           -0.000219  1.144856  0.906069
Lasso                -0.000219  1.144856  0.906069

In [39]:
# XGB yi bizde tek başına deneyelim.
from xgboost import XGBRegressor

In [43]:
model=XGBRegressor()
model.fit(x_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

In [44]:
tahmin = model.predict(x_test)

In [45]:
r2 = r2_score(y_test, tahmin)
mse = mean_squared_error(y_test, tahmin)
mae = mean_absolute_error(y_test, tahmin)

print(f"XGBoost Test R² Skoru: {r2:.4f}")
print(f"Mean Squared Error (MSE): {mse:.4f}")
print(f"Mean Absolute Error (MAE): {mae:.4f}")

XGBoost Test R² Skoru: 0.8367
Mean Squared Error (MSE): 0.2140
Mean Absolute Error (MAE): 0.3107

In [47]:
# pickle ile turşusunu kuralım modelin
import pickle

pickle.dump(model, open("CaliforniaHousing_xgb_model.pkl", "wb"))
pickle.dump(scaler, open("CaliforniaHousing_xgb_scaler.pkl", "wb"))

In [48]:
# Modeli XGB nin kendi yerle formatında kaydedelim
model.save_model("CaliforniaHousing_xgb_model.json")